// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared.Data;

#nullable disable

namespace Shared.Data.Migrations
{
    [DbContext(typeof(L3FContext))]
    [Migration("20240316165801_CargaInicial")]
    partial class CargaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.ContaPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdRegraContasPagar")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorCorrigido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdRegraContasPagar")
                        .IsUnique()
                        .HasFilter("[IdRegraContasPagar] IS NOT NULL");

                    b.ToTable("ContasAPagar");
                });

            modelBuilder.Entity("Shared.Models.RegrasContasPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("JurosDiaPercentual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("JurosDiaValor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MultaPercentual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MultaValor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorCorrigido")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("RegraContasAPagar");
                });

            modelBuilder.Entity("Shared.Models.ContaPagar", b =>
                {
                    b.HasOne("Shared.Models.RegrasContasPagar", "RegraContasPagar")
                        .WithOne("ContaPagar")
                        .HasForeignKey("Shared.Models.ContaPagar", "IdRegraContasPagar");

                    b.Navigation("RegraContasPagar");
                });

            modelBuilder.Entity("Shared.Models.RegrasContasPagar", b =>
                {
                    b.Navigation("ContaPagar")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
